[workspace]
members = [
    "covert-types",
    "covert-storage",
    "covert-framework",
    "covert-server",
    "covert-cli",
    "covert-sdk",
    "backend/covert-kv",
    "backend/covert-psql",
    "backend/covert-userpass-auth",
]
resolver = "2"
