port = 8080
storage-path = "./tmp-db-storage"

# MinIO example
[replication]
access-key-id = "minioadmin"
secret-access-key = "minioadmin"
bucket = "mybkt"
endpoint = "http://localhost:9000"
region = "eu-west-1"
prefix = "foobar"

# S3 example
# [replication]
# access-key-id = ""
# secret-access-key = ""
# bucket-url = "s3://<BUCKET>/<PATH>/"
# region = "eu-west-1"
# prefix = "foobar"