on: [push]

name: CI

jobs:
  build_and_test:
    name: Covert test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Format
        with:
          command: fmt
          args: --all --check
      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: --all --all-features
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --all --all-targets --all-features
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --release --all-features